---
title: "Xiao_HW4"
format: html
editor: visual
---

#### Task 1: Conceptual Questions

1.  Rewrite the following nested function call using baseR's chaining operator:

library(tidyverse) arrange(filter(select(as_tibble(iris), starts_with("Petal"), Species), Petal.Length \< 1.55), Species)

```{r}
as_tibble(iris) |>
  select(starts_with("Petal"), Species) |>
  filter(Petal.Length < 1.55) |>
  arrange(Species)
```

2.  What is meant by long format data and wide format data? Which do we generally prefer for statistical analysis?

Long format data refers to multiple rows for each observational unit (e.g. recurring ID numbers for test scores such as math/reading)--this is generally the preferred format for statistical analysis because it is expected by many R functions from visualization libraries (ggplot2) to statistical modeling functions (lm/ANOVA/mixed effects models).

Wide format data generally has one row for each observational unit with different measurements separated by columns (e.g. one ID number followed by a math column and a reading column).

#### Task 2: Note: Use Chaining where possible!

#### Glass data

3.  Start a chain on your data object that overwrites the Type_of_glass variable using mutate().

4.  Continue your chain and keep only observations where the Fe variable is less than 0.2 and the Type of Glass is either "tableware" or "headlamp".

#### Yeast data

5.  Start a chain that removes the seq_name and nuc columns.

6.  Continue your chain to add columns corresponding to the mean and median of each numeric variable (mcg, gvh, alm, mit, erl, pox, and vac) at each class grouping (see the across() function)

#### Wine data

7.  Start a chain on your new combined data object to filter the data to only look at high-quality wines (quality \> 6.5) and wines that have a reasonable alcohol value (alcohol \< 132)

8.  Continue your chain to now sort the data from highest quality to lowest.

9.  Continue your chain to select only the variables that contain acid, the alochol variable, the type variable and the quality variable.

10. Continue your chain to add the mean and standard deviation of the alcohol variable to the data set for each setting of the quality variable.

#### Task 3: Databse Practice

Download the Lahman.db file associated with the Connecting to Databases notes/video.

11. Connect to the database and then look at all of the tables in the database.

12. Use the tbl() function and dplyr to return all of the data from the Teams table for the year 2015.

13. Repeat the above by using the sql() function within tbl() (here you have to write actual SQL)

#### Either use dplyr or write SQL queries for the rest of these questions.

14. Return all of the players in the hall of fame, the year they were voted into the hall of fame, and their category (only those three variables). See the HallOfFame table, the inducted variable is important here.

15. Combine the table from the previous question with the People table in order to have the nameFirst and nameLast names added to what was returned above.

16. Return only the playerID (manager ID), G, W, and L columns from the Managers table. Use chaining to then determine the overall win/loss records (sum of wins & sum of losses) for each of these hall of fame managers using group_by() with summarize() rather than mutate. Create a new variable that is the career win/loss percentage as column Total_W/G_managed. Sort the resulting data by the win/loss percentage variable (from largest to smallest).

17. Use the results from the previous two questions to answer this one! Return information for only the people that managed a team and were inducted into the hall of fame (regardless of their category in the hall of fame - you want to return all people in the hall of fame that ever managed at all). (Just return all of the variables from both of the above two questions - 9 total columns
